version: '3'
services:
    nginx:
        restart: always
        image: 'arindamhalder/multi-nginx'
        ports:
           - '3050:80'
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    api:
        image: 'arindamhalder/multi-server'
        environment:
              - REDIS_HOST=redis
              - REDIS_PORT=6379
              - PGUSER=postgres
              - PGHOST=postgres
              - PGDATABASE=postgres
              - PGPASSWORD=postgres_password
              - PGPORT=5432

    client:
        image: 'arindamhalder/multi-client'
    worker:
        image: 'arindamhalder/multi-worker'
        environment:
              - REDIS_HOST=redis
              - REDIS_PORT=6379

